#!/usr/bin/env php
<?php
/**
 * Pop Kettle Console Application
 */

$autoloader = include __DIR__ . '/vendor/autoload.php';

$dotEnv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotEnv->safeLoad();

try {
    if (file_exists('kettle.inc.php')) {
        include 'kettle.inc.php';
    }

    // Load any custom application command routes
    $config           = include __DIR__ . '/config/app.console.php';
    $config['routes'] = Pop\Kettle\Module::loadCommandRoutes($config['routes']);

    $app = new Pop\Application($autoloader, $config);
    $app->register(new Pop\Kettle\Module());
    $app->run();
} catch (\Exception $exception) {
    $app = new Pop\Kettle\Module();
    $app->cliError($exception);
}
