#!/usr/bin/env php
<?php

$autoloader = include __DIR__ . '/../vendor/autoload.php';
$autoloader->addPsr4('MyApp\\', __DIR__ . '/../app/src');

$dotEnv = Dotenv\Dotenv::createImmutable(__DIR__ . '/../');
$dotEnv->safeLoad();

try {
    // Load any custom application command routes
    $config           = include __DIR__ . '/../app/config/app.console.php';
    $config['routes'] = Pop\Console\CommandRegistry::loadRoutes($config['routes'], __DIR__ . '/../app/src/Console/Command');

    $app = new Pop\Application($autoloader, $config);
    $app->load();
    $app->run();
} catch (\Exception $exception) {
    $app = new MyApp\Application();
    $app->cliError($exception);
}


